=== iqrf/iqrf-gateway-webapp/api/schemas/networkConnection.json
{
	"$schema": "http://json-schema.org/draft-07/schema",
	"$id": "https://apidocs.iqrf.org/iqrf-gateway-webapp-api/schemas/networkConnection.json",
	"type": "object",
	"title": "Network connection detail",
	"additionalProperties": false,
	"required": [
		"name",
		"uuid",
		"type",
		"interface",
		"autoConnect",
		"ipv4",
		"ipv6"
	],
	"properties": {
		"name": {
			"$id": "#/properties/name",
			"type": "string",
			"title": "Connection name",
			"example": "Wired connection 1"
		},
		"uuid": {
			"$id": "#/properties/uuid",
			"type": "string",
			"title": "Connection UUID",
			"example": "c8fb6f29-ec85-4ff5-b1bb-1d1761196d16"
		},
		"type": {
			"$id": "#/properties/type",
			"type": "string",
			"enum": [
				"bluetooth",
				"bridge",
				"dummy",
				"802-3-ethernet",
				"gsm",
				"infiniband",
				"tun",
				"vlan",
				"vpn",
				"802-11-wireless",
				"wimax",
				"wireguard",
				"wpan"
			],
			"title": "Connection type",
			"example": "802-3-ethernet"
		},
		"interface": {
			"$id": "#/properties/interface",
			"type": "string",
			"title": "Interface name",
			"example": "eth0"
		},
		"autoConnect": {
			"$id": "#/properties/autoConnect",
			"type": "object",
			"title": "Automatic connecting",
			"example": {
				"enabled": true,
				"priority": 0,
				"retries": -1
			},
			"additionalProperties": false,
			"required": [
				"enabled",
				"priority",
				"retries"
			],
			"properties": {
				"enabled": {
					"$id": "#/properties/autoConnect/properties/enabled",
					"type": "boolean",
					"title": "Automatic connecting enablement",
					"example": true
				},
				"priority": {
					"$id": "#/properties/autoConnect/properties/priority",
					"type": "integer",
					"title": "Connection priority",
					"example": 0
				},
				"retries": {
					"$id": "#/properties/autoConnect/properties/retries",
					"type": "integer",
					"title": "Connection retries",
					"example": -1
				}
			}
		},
		"ipv4": {
			"$id": "#/properties/ipv4",
			"type": "object",
			"title": "IPv4 connection",
			"example": {
				"dns": [
					{
						"address": "192.168.1.1"
					}
				],
				"addresses": [
					{
						"mask": "255.255.255.0",
						"prefix": 24,
						"address": "192.168.1.198"
					}
				],
				"gateway": "192.168.1.1",
				"method": "manual"
			},
			"additionalProperties": false,
			"required": [
				"method",
				"addresses",
				"gateway",
				"dns"
			],
			"properties": {
				"method": {
					"$id": "#/properties/ipv4/properties/method",
					"type": "string",
					"enum": [
						"auto",
						"disabled",
						"link-local",
						"manual",
						"shared"
					],
					"title": "IPv4 connection method",
					"example": "manual"
				},
				"addresses": {
					"$id": "#/properties/ipv4/properties/addresses",
					"type": "array",
					"title": "IPv4 addresses",
					"example": [
						{
							"prefix": 24,
							"address": "192.168.1.198",
							"mask": "255.255.255.0"
						}
					],
					"additionalItems": false,
					"items": {
						"$id": "#/properties/ipv4/properties/addresses/items",
						"type": "object",
						"title": "IPv4 address",
						"example": {
							"address": "192.168.1.198",
							"mask": "255.255.255.0",
							"prefix": 24
						},
						"additionalProperties": false,
						"required": [
							"address",
							"prefix",
							"mask"
						],
						"properties": {
							"address": {
								"$id": "#/properties/ipv4/properties/addresses/items/properties/address",
								"type": "string",
								"format": "ipv4",
								"title": "IPv4 address",
								"example": "192.168.1.198"
							},
							"prefix": {
								"$id": "#/properties/ipv4/properties/addresses/items/properties/prefix",
								"type": "integer",
								"minimum": 1,
								"maximum": 32,
								"title": "IPv4 network prefix",
								"example": 24
							},
							"mask": {
								"$id": "#/properties/ipv4/properties/addresses/items/properties/mask",
								"type": "string",
								"format": "ipv4",
								"title": "IPv4 network mask",
								"example": "255.255.255.0"
							}
						}
					}
				},
				"gateway": {
					"$id": "#/properties/ipv4/properties/gateway",
					"oneOf": [
						{
							"type": "string"
						},
						{
							"type": "null"
						}
					],
					"format": "ipv4",
					"title": "IPv4 gateway address",
					"example": "192.168.1.1"
				},
				"dns": {
					"$id": "#/properties/ipv4/properties/dns",
					"type": "array",
					"title": "DNS IPv4 addresses",
					"example": [
						{
							"address": "192.168.1.1"
						}
					],
					"additionalItems": false,
					"items": {
						"$id": "#/properties/ipv4/properties/dns/items",
						"type": "object",
						"title": "DNS IPv4 address",
						"example": {
							"address": "192.168.1.1"
						},
						"additionalProperties": false,
						"required": [
							"address"
						],
						"properties": {
							"address": {
								"$id": "#/properties/ipv4/properties/dns/items/properties/address",
								"type": "string",
								"format": "ipv4",
								"title": "IPv4 address",
								"example": "1.1.1.1"
							}
						}
					}
				}
			}
		},
		"ipv6": {
			"$id": "#/properties/ipv6",
			"type": "object",
			"title": "IPv6 connection",
			"example": {
				"addresses": [
					{
						"prefix": 64,
						"gateway": "fe80::6f0:21ff:fe24:1e53",
						"address": "2001:470:5bb2::671"
					}
				],
				"method": "manual",
				"dns": [
					{
						"address": "2606:4700:4700::1111"
					}
				]
			},
			"additionalProperties": false,
			"required": [
				"method",
				"addresses",
				"gateway",
				"dns"
			],
			"properties": {
				"method": {
					"$id": "#/properties/ipv6/properties/method",
					"type": "string",
					"enum": [
						"auto",
						"disabled",
						"dhcp",
						"ignore",
						"link-local",
						"manual",
						"shared"
					],
					"title": "IPv6 connection method",
					"example": "manual"
				},
				"addresses": {
					"$id": "#/properties/ipv6/properties/addresses",
					"type": "array",
					"title": "IPv6 addresses",
					"example": [
						{
							"prefix": 64,
							"gateway": "fe80::6f0:21ff:fe24:1e53",
							"address": "2001:470:5bb2::671"
						}
					],
					"additionalItems": false,
					"items": {
						"$id": "#/properties/ipv6/properties/addresses/items",
						"type": "object",
						"title": "IPv6 address",
						"examples": [
							{
								"prefix": 64,
								"gateway": "fe80::6f0:21ff:fe24:1e53",
								"address": "2001:470:5bb2::671"
							}
						],
						"additionalProperties": false,
						"required": [
							"address",
							"prefix"
						],
						"properties": {
							"address": {
								"$id": "#/properties/ipv6/properties/addresses/items/properties/address",
								"type": "string",
								"title": "IPv6 address",
								"example": "2001:470:5bb2::671"
							},
							"prefix": {
								"$id": "#/properties/ipv6/properties/addresses/items/properties/prefix",
								"type": "integer",
								"title": "IPv6 network prefix",
								"example": 64
							}
						}
					}
				},
				"gateway": {
					"$id": "#/properties/ipv6/properties/addresses/items/properties/gateway",
					"oneOf": [
						{
							"type": "string"
						},
						{
							"type": "null"
						}
					],
					"format": "ipv6",
					"title": "IPv6 gateway address",
					"example": "fe80::6f0:21ff:fe24:1e53"
				},
				"dns": {
					"$id": "#/properties/ipv6/properties/dns",
					"type": "array",
					"title": "DNS IPv6 addresses",
					"examples": [
						{
							"address": "2606:4700:4700::1111"
						}
					],
					"additionalItems": false,
					"items": {
						"$id": "#/properties/ipv6/properties/dns/items",
						"type": "object",
						"title": "DNS IPv6 address",
						"example": {
							"address": "2606:4700:4700::1111"
						},
						"additionalProperties": false,
						"required": [
							"address"
						],
						"properties": {
							"address": {
								"$id": "#/properties/ipv6/properties/dns/items/properties/address",
								"type": "string",
								"format": "ipv6",
								"title": "IPv6 address",
								"example": "2606:4700:4700::1111"
							}
						}
					}
				}
			}
		},
		"wifi": {
			"$id": "#/properties/wifi",
			"type": "object",
			"title": "WiFi connection",
			"example": {
				"ssid": "WIFI MAGDA",
				"mode": "infrastructure",
				"security": {
					"keyManagement": "wpa-psk",
					"psk": "password"
				}
			},
			"additionalProperties": false,
			"required": [
				"ssid",
				"mode",
				"security"
			],
			"properties": {
				"ssid": {
					"$id": "#/properties/wifi/properties/ssid",
					"type": "string",
					"title": "SSID",
					"description": "Service Set Identifier",
					"example": "WIFI MAGDA"
				},
				"mode": {
					"$id": "#/properties/wifi/properties/mode",
					"type": "string",
					"title": "Network mode",
					"enum": [
						"adhoc",
						"ap",
						"infrastructure",
						"mesh"
					],
					"example": "infrastructure"
				},
				"security": {
					"$id": "#/properties/wifi/security",
					"type": "object",
					"title": "WiFi connection security",
					"example": {
						"type": "wpa-psk",
						"psk": "password"
					},
					"additionalProperties": false,
					"required": [
						"type"
					],
					"properties": {
						"type": {
							"$id": "#/properties/wifi/properties/security/properties/type",
							"type": "string",
							"title": "Security type",
							"enum": [
								"open",
								"wep",
								"leap",
								"wpa-eap",
								"wpa-psk"
							],
							"example": "wpa-psk"
						},
						"leap": {
							"$id": "#/properties/wifi/properties/security/properties/leap",
							"type": "object",
							"title": "Cisco LEAP",
							"additionalProperties": false,
							"required": [
								"username",
								"password"
							],
							"properties": {
								"username": {
									"$id": "#/properties/wifi/properties/security/properties/leap/username",
									"type": "string",
									"title": "Cisco LEAP username",
									"example": "username"
								},
								"password": {
									"$id": "#/properties/wifi/properties/security/properties/leap/password",
									"type": "string",
									"title": "Cisco LEAP password",
									"example": "password"
								}
							}
						},
						"wep": {
							"$id": "#/properties/wifi/properties/security/properties/wep",
							"type": "object",
							"title": "WEP",
							"additionalProperties": false,
							"required": [
								"type",
								"index",
								"keys"
							],
							"properties": {
								"type": {
									"$id": "#/properties/wifi/properties/security/properties/wep/type",
									"type": "string",
									"title": "WEP key type",
									"enum": [
										"key",
										"passphrase",
										"unknown"
									],
									"example": "key"
								},
								"index": {
									"$id": "#/properties/wifi/properties/security/properties/wep/index",
									"type": "integer",
									"title": "WEP transfer key index",
									"minimum": 0,
									"maximum": 3,
									"example": 0
								},
								"keys": {
									"$id": "#/properties/wifi/properties/security/properties/wep/keys",
									"type": "array",
									"title": "WEP keys",
									"minItems": 4,
									"maximum": 4,
									"additionalItems": false,
									"items": {
										"$id": "#/properties/wifi/properties/security/properties/wep/keys/items",
										"type": "string",
										"title": "WEP key",
										"example": "4b70797e57534a5c4833493352"
									}
								}
							}
						},
						"psk": {
							"$id": "#/properties/wifi/properties/security/properties/psk",
							"type": "string",
							"title": "Pre-shared key",
							"example": "password"
						}
					},
					"allOf": [
						{
							"if": {
								"properties": {
									"type": {
										"const": "leap"
									}
								}
							},
							"then": {
								"required": [
									"type",
									"leap"
								]
							}
						},
						{
							"if": {
								"properties": {
									"type": {
										"const": "wep"
									}
								}
							},
							"then": {
								"required": [
									"type",
									"wep"
								]
							}
						},
						{
							"if": {
								"properties": {
									"type": {
										"const": "wpa-psk"
									}
								}
							},
							"then": {
								"required": [
									"type",
									"psk"
								]
							}
						}
					]
				}
			}
		}
	},
	"allOf": [
		{
			"if": {
				"properties": {
					"type": {
						"const": "802-11-wireless"
					}
				}
			},
			"then": {
				"required": [
					"name",
					"uuid",
					"type",
					"interface",
					"ipv4",
					"ipv6",
					"wifi"
				]
			}
		}
	]
}

=== iqrf/iqrf-gateway-webapp/tests/data/networkManager/toForm/25ab1b06-2a86-40a9-950f-1c576ddcd35a.json
{
	"name": "eth0",
	"uuid": "25ab1b06-2a86-40a9-950f-1c576ddcd35a",
	"type": "802-3-ethernet",
	"interface": "eth0",
	"autoConnect": {
		"enabled": true,
		"priority": 0,
		"retries": -1
	},
	"ipv4": {
		"method": "manual",
		"addresses": [
			{
				"address": "192.168.1.2",
				"prefix": 24,
				"mask": "255.255.255.0"
			}
		],
		"gateway": "192.168.1.1",
		"dns": [
			{
				"address": "192.168.1.1"
			}
		]
	},
	"ipv6": {
		"method": "manual",
		"addresses": [
			{
				"address": "2001:470:5bb2::2",
				"prefix": 64
			}
		],
		"gateway": "fe80::1",
		"dns": [
			{
				"address": "2001:470:5bb2::1"
			}
		]
	}
}
